---
language: ruby
sudo: false
cache:
  directories:
    - vendor/bundle
script:
  - bundle exec rake spec
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: 2.1.5
notifications:
  email: false
